
DELETE http://localhost:3000/cars/repairs/2
content-type: application/json

{
    "descOfRepair": "test2",
    "details": "test2",
    "cost": 2002,
    "fromDate": "2023-01-29T15:00:25.000Z",
    "toDate": "2023-01-29T15:00:25.000Z"
    }